#Problem Set 1
#Due January 30, 10AM
#Isaac Lee, 438148
#GRADE:16/15
###1. Open the dataset as a dataframe
#Good
getwd()
setwd('/Users/isaacl/Dropbox (Work)/PS4625 Data/PS/PS1/')
ps1data <- read.csv('Expends2002.csv')
dim(ps1data)
###2. Change variable name TransID to Useless
#Good
names(ps1data)[names(ps1data) == 'TransID'] <- 'Useless'
colnames(ps1data)
###3. Remove the variable Uselsss, and Source from the dataframe
#Good
ps1data$Useless <- NULL
ps1data$Source <- NULL

###4. Change the variable EntType to a factor. How many levels does this variable have?
#Good
ps1data$EntType <- factor (ps1data$EntType)
levels(ps1data$EntType)
#EntType has 8 levels: "", "CAN", "CCM", "COM", "IND", "ORG", "PAC", "PTY"

###5. Incorrect States
#Good
unique(ps1data$State)
states_ps1data<-unique(c(as.character(ps1data$State)))
states50 <- c('AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA','HI','ID','IL','IN',
              'IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH',
              'NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT',
              'VT','VA','WA','WV','WI','WY','VI','GU', 'AS')
#leaving VI virgin islands, GU guam, AS american samoa in the dataset.
states_ps1data[!(states_ps1data %in% states50)]
#if territories are not removed, then St, ZZ, LL are the only non-existent state codes. 
ps1data[ps1data$State == 'St',]
#Data shows the only row with State Code 'St' is Thurman for Congress, which is in FL, so we re-set state code to FL.
ps1data$State[8994] <- "FL"
ps1data[ps1data$State == 'ZZ',]
#Data shows the only row with State Code "ZZ' Is Republican Party of Virgin Islands with City set as Kingshill VI, so we should also set state code to VI.
ps1data$State[12333] <- "VI"
ps1data[ps1data$State == 'LL',]
#Data shows the only row with State Code 'LL' is Republican Party of Iowa, so we set state code as IA.
ps1data$State[12983] <- "IA"

###6. Remove observations where variable State is missing.
#Good
#Report number of observations after removing missing values. 
ps1data[ps1data$State == "  ",]
ps1data<-ps1data[!(ps1data$State=="  "),]
#The number of observations after removing missing values is 19912 observations.

####7 Change variable Zip into a numeric. Be sure to document what you do with missing cases. 
#Good
#What is the mean of this variable?
class(ps1data$Zip)
ps1data$Zip<-as.numeric(ps1data$Zip)
class(ps1data$Zip)
mean(ps1data$Zip, na.rm = TRUE)
#mean of this variable is 2937.9
#I left missing cases in the numeric set, but ignored them from mean calculation by using na.rm=TRUE

###8 Create new variables that contain the following information and answer the following q's
#Good
#The number of words in the Descrip Variable. What is the median value of this new variable?
df <-NULL
df$Descrip<-ps1data$Descrip
df<- as.data.frame(df)
df$DescripNumWord<- sapply(df$Descrip, function(x) length(unlist(strsplit(as.character(x), "\\W+"))))
sum(df$DescripNumWord) 
median(df$DescripNumWord)
#The median value of this new variable is 2.

#Variable containing the numeric portion of CRPFilerid. Should be length 8. What is the number of unique values of this variable?
#Good
df$CRPFilerid<-ps1data$CRPFilerid
df$CRPFilerid_Num<-substr(df$CRPFilerid,2,9)
length(unique(df$CRPFilerid_Num))
#THere are 2243 Unique Values of this variable.

#A vector containing the first four digits of Zip. What is the most frequent value of this vector?
#Good

df$Zip<-ps1data$Zip
df$Zip_FirstFour <- substr(ps1data$Zip,0,4)
tail(names(sort(table(df$Zip_FirstFour))), 1)
#1257 is the most fequent value of this Zip vector

#A boolean indicating whether the Descrip variable contains the world Communications, regardless of capitalization. Report the number of TRUE values
#Good
df$Descrip
df$Descrip_nchar<-nchar(as.character(df$Descrip))
df$Descrip_gsub_nchar<-nchar(gsub("Communications","",as.character(df$Descrip),ignore.case = T))
df$IfCommunications<-ifelse(df$Descrip_nchar!=df$Descrip_gsub_nchar,T,F)
df$IfCommunications
sum(df$IfCommunications == T)
#There are 9 True values, meaning there are 9 rows in the Descrip variable that contains Communications.

#A variable indicating that either CRPFilerid is "N" or that BOTH Amount is greater than 500 and Descrip is non-missing. Report the number of TRUE values
#Good
df$firstLeter = substr(ps1data$CRPFilerid, 1, 1)
df$Amount = ps1data$Amount
df$Q9P5 = df$firstLeter == "N" | (df$Amount > 500 & !is.na(df$Descrip))
sum(df$Q9P5 == T)
#There are 13360 True values that meet the condition listed above (CRPFilerid is N or BOTH Amount > 500 & Descrip is non-missing.)

#Extra Credit: Variable that provides the most common letter in Descrip variable
#Good
DescripLetters<-paste(unlist(df$Descrip), collapse =" ")
max(sapply(letters, function(x) x<-sum(x==unlist(strsplit(DescripLetters,"")))))
#The table generated by the above line shows that "E" is the most common letter in the Descrip variable

###9 Write a script that subsets the data by state, and writes out a unique CSV file for each subset, where each file has a unique and meaningful name
#newData <- by(ps1data,ps1data$State,function(x) ps1data)
#by(ps1data, ps1data$State, write.csv, file = paste0(levels(ps1data$State), ".csv"))
#Good
for(level in levels(ps1data$State)) {
  tempdata = ps1data[ps1data$State == level, ]
  write.csv(tempdata, file=paste0(level, ".csv"))
}


